routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(["middleware" => ["web"]], function(){
    Route::get('test', 'TestController@index');
    Route::view('installation-guide', 'pages.installation_guide.index')->name('installation_guide');

    /* Plan and Pricing */
    Route::group(["middleware" => ["auth.shopify"],"prefix" => "choose-plan"], function(){
        Route::get("/", "ChoosePlan\ChoosePlanController@index")->name('choose.plan.index');
        Route::get("/free", "ChoosePlan\ChoosePlanController@chooseFreePlan")->name('choose.plan.free');
    });

    Route::group(["middleware" => ["auth.shopify", "check.plan"]], function() {

        /* Get Shopify Discount Codes */
        Route::get("/get-discount-codes", function(Request $request){
            $discounts = getDiscountCodes($request);
            return response($discounts,Illuminate\Http\Response::HTTP_OK);
        })->name('discount.code');

        /* Dashboard */
        Route::get("/","Dashboard\DashboardController@index")->name('home');

        /* Earning Points / Rules */
        Route::group(["prefix" => "earning-points"], function() {
            Route::get("/","EarningPoints\EarningPointsController@index")->name('earning-points.index');
            Route::get("/edit/{id}","EarningPoints\EarningPointsController@edit")->name('earning-points.edit');
            Route::post("/update/{id}","EarningPoints\EarningPointsController@update")->name('earning-points.update');
        });

        /* Customers */
        Route::group(["namespace"=> "Customers"], function() {
            Route::resource("/customers","CustomersController");
        });

        /* Customer Level */
        Route::group(["namespace"=> "CustomerLevel"], function() {
            Route::resource("/customer-level","CustomerLevelController");
        });

        /* Campaign  */
        Route::group(["namespace"=> "Campaign"], function() {
            Route::resource("/campaign","CampaignController");
        });

        /* Display Setting  */
        Route::group(["namespace"=> "DisplaySetting"], function() {
            Route::resource("/display-setting","DisplaySettingController");
        });

    });
});

Route::get('flush', function(){
    request()->session()->flush();
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name') }}</title>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{{asset('css/app.css')}}" type="text/css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    @if(config('shopify-app.appbridge_enabled'))
        <script src="https://unpkg.com/@shopify/app-bridge"></script>
        <script>
            var AppBridge = window['app-bridge'];
            var createApp = AppBridge.default;

            window.shopify_app_bridge = createApp({
                apiKey: '{{ config('shopify-app.api_key') }}',
                shopOrigin: '{{ Auth::user()->name }}',
                forceRedirect: true,
            });
        </script>
    @endif
</head>
<body>
@php
    $earning = \App\Models\EarningPoint::whereUserId(\Auth::user()->id)->whereStatus(1)->count();
@endphp
@include('layouts.aside')
<div class="app-content" id="app" @if(!$earning) style="width:100%;margin-left: unset;" @endif>
    @yield('content')

</div>

<script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/aside.blade.php
<div class="app-header">
    <a class="app-brand" href="#"><b><i>Shoployal</i></b></a>
</div>

@if($earning)
    <div class="app-sidebar">
        <ul class="list-unstyled">
            <li>
                <a href="{{ route("home") }}" class="active">
                    <span><i class="material-icons app-side-icon">home</i>Home</span>
                </a>

            </li>
            <li class="submenu">
                <a href="#">
                    <span><i class="material-icons app-side-icon">people</i>Customers</span>
                </a>
                <ul class="list-unstyled">
                    <li><a href="{{ route("customers.index") }}">All Customers</a></li>
                    <li><a href="{{ route("customer-level.index") }}">Customer Levels</a></li>
                </ul>
            </li>
            <li>
                <a href="{{ route("campaign.index") }}">
                    <span><i class="material-icons app-side-icon">view_list</i>Campaigns</span>
                </a>
            </li>
            <li class="submenu">
                <a href="#">
                    <span><i class="material-icons app-side-icon">settings</i>Settings</span>
                </a>
                <ul class="list-unstyled">
                    <li><a href="{{ route("earning-points.index") }}">Reward program</a></li>
                    <li><a href="{{ route("display-setting.index") }}">Display Settings</a></li>
                </ul>
            </li>

            <li>
                <a href="{{ route("choose.plan.index") }}">
                    <span><i class="material-icons app-side-icon">settings</i>Subscription Plans</span>
                </a>
            </li>

            <li>
                <a href="{{ route("installation_guide") }}">
                    <span><i class="material-icons app-side-icon">settings</i>Installation Guide</span>
                </a>
            </li>
        </ul>
    </div>
    <script>
        $('.bars').click(function(){
            $(this).toggleClass('active');
            $('.app-sidebar').toggleClass('active');
        });

        $('.submenu > a').click(function(){
            $(this).parents('.submenu').toggleClass('active');
        });
    </script>
@endif